//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineHospitalSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppointmentsTable
    {
        public int AppointmentID { get; set; }
        public int DoctorID { get; set; }
        public int PatientID { get; set; }
        public System.DateTime AppointmentDate { get; set; }
        public System.TimeSpan AppointmentTime { get; set; }
        public int DepartmentID { get; set; }
        public int HospitalID { get; set; }
    
        public virtual DoctorTable DoctorTable { get; set; }
        public virtual HospitalTable HospitalTable { get; set; }
        public virtual PatientTable PatientTable { get; set; }
    }
}
