//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineHospitalSystem
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AurumStellaEntities : DbContext
    {
        public AurumStellaEntities()
            : base("name=AurumStellaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AppointmentsTable> AppointmentsTables { get; set; }
        public virtual DbSet<DepartmentTable> DepartmentTables { get; set; }
        public virtual DbSet<DoctorTable> DoctorTables { get; set; }
        public virtual DbSet<HospitalTable> HospitalTables { get; set; }
        public virtual DbSet<MessagesTable> MessagesTables { get; set; }
        public virtual DbSet<PatientTable> PatientTables { get; set; }
    }
}
