//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineHospitalSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessagesTable
    {
        public int MessageID { get; set; }
        public string FROM { get; set; }
        public string TO { get; set; }
        public string MessageText { get; set; }
    }
}
